spring.application.name=ebank-bot
spring.main.web-application-type=servlet
spring.ai.openai.api-key=${botebank}
spring.ai.openai.chat.options.model=gpt-4o
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
server.port=8058